services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - crisis_data:/data/db  # Persistent volume for MongoDB data

  backend:
    build:
      context: ./crisisfacts_summarization
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    ports:
      - "5001:5000"  # Expose first Flask app on port 5000

  frontend:
    build:
      context: ./app  # Directory containing React app
      dockerfile: Dockerfile  # React app Dockerfile
    container_name: frontend_service
    ports:
      - "3000:3000"  # Expose port 3000 for React app
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes:
      - ./app:/app/

volumes:
  crisis_data:
    driver: local  # Persistent named volume